### PR TITLE
Update to be somewhat closer to pairty with

### PR DESCRIPTION
**Pull request by runningferret**
the mojolingo codebase

### CODE REVIEW

**Comment by runningferret** [comment]
@sfgeorge @jared-prime

**Comment by sfgeorge** [comment]
Groovy :+1:

**Comment by ajayanty** [comment]
@jared-prime please review for final approval

**Comment by Jared-Prime** [comment]
:+1:

**Comment by ajayanty** [comment]
This has been merged into cloudvox:develop-ifbyphone

**Pull request merged**
