### PR TITLE
[BUGFIX] Recognition-Timeout must be > 0

### PR DESCRIPTION
**Pull request by Jared-Prime**
Fixes [DE1947](https://rally1.rallydev.com/#/8108440228ud/detail/defect/20634687730)

### CODE REVIEW

**Comment by Jared-Prime** [comment]
@sfgeorge @runningferret

**Comment by runningferret** [comment]
:+1:

**Comment by sfgeorge** [comment]
Groovy :+1:

@ajayanty Can you merge this for us?

**Comment by sfgeorge** [comment]
@ajayanty We're blocked on this.  Can you merge for us?  Thanks man.

**Comment by ajayanty** [comment]
This has been merged into cloudvox:develop-ifbyphone

**Pull request merged**
