### PR TITLE
DE1687 long tts in fallback

### PR DESCRIPTION
**Pull request by Jared-Prime**
Allow fallback text to play long TTS

### CODE REVIEW

**Comment by Jared-Prime** [comment]
@sfgeorge please review

**Comment by sfgeorge** [comment]
Excellent fix.  Though, the `release/phoenix/2.0.1` branch of our Punchblock fork includes #1, which has not been tested.  Can you re-open this PR and target against the newly created `release/phoenix/2.0.2` branch?

**Comment by Jared-Prime** [comment]
closing to target against `release/phoenix/2.0.2`

**Comment by sfgeorge** [comment]
Looks good! :+1: 

@ajayanty Can you merge this for us?  This can be merged immediately.  It will not go out this week even if you change it.

This is similar to an Ifbyphone library change... it doesn't become active until will reference it in in the `ahn/Gemfile.lock` file in apptastic (very similar to CRBN's composer.lock).

We will update apptastic's `ahn/Gemfile.lock` in Sprint 31, not this week.

**Comment by ajayanty** [comment]
This has been merged into  cloudvox:release/phoenix/2.0.1

**Pull request merged**
